import type { CountryMeta } from './types'

// ISO-2 → { name, flag emoji }
// Covers all 249 ISO 3166-1 alpha-2 codes + common territories
const COUNTRIES: CountryMeta[] = [
  { iso2: 'AF', name: 'Afghanistan', flag: '🇦🇫' },
  { iso2: 'AL', name: 'Albania', flag: '🇦🇱' },
  { iso2: 'DZ', name: 'Algeria', flag: '🇩🇿' },
  { iso2: 'AD', name: 'Andorra', flag: '🇦🇩' },
  { iso2: 'AO', name: 'Angola', flag: '🇦🇴' },
  { iso2: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬' },
  { iso2: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { iso2: 'AM', name: 'Armenia', flag: '🇦🇲' },
  { iso2: 'AU', name: 'Australia', flag: '🇦🇺' },
  { iso2: 'AT', name: 'Austria', flag: '🇦🇹' },
  { iso2: 'AZ', name: 'Azerbaijan', flag: '🇦🇿' },
  { iso2: 'BS', name: 'Bahamas', flag: '🇧🇸' },
  { iso2: 'BH', name: 'Bahrain', flag: '🇧🇭' },
  { iso2: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { iso2: 'BB', name: 'Barbados', flag: '🇧🇧' },
  { iso2: 'BY', name: 'Belarus', flag: '🇧🇾' },
  { iso2: 'BE', name: 'Belgium', flag: '🇧🇪' },
  { iso2: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { iso2: 'BJ', name: 'Benin', flag: '🇧🇯' },
  { iso2: 'BT', name: 'Bhutan', flag: '🇧🇹' },
  { iso2: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  { iso2: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { iso2: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { iso2: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { iso2: 'BN', name: 'Brunei', flag: '🇧🇳' },
  { iso2: 'BG', name: 'Bulgaria', flag: '🇧🇬' },
  { iso2: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { iso2: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { iso2: 'CV', name: 'Cape Verde', flag: '🇨🇻' },
  { iso2: 'KH', name: 'Cambodia', flag: '🇰🇭' },
  { iso2: 'CM', name: 'Cameroon', flag: '🇨🇲' },
  { iso2: 'CA', name: 'Canada', flag: '🇨🇦' },
  { iso2: 'CF', name: 'Central African Republic', flag: '🇨🇫' },
  { iso2: 'TD', name: 'Chad', flag: '🇹🇩' },
  { iso2: 'CL', name: 'Chile', flag: '🇨🇱' },
  { iso2: 'CN', name: 'China', flag: '🇨🇳' },
  { iso2: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { iso2: 'KM', name: 'Comoros', flag: '🇰🇲' },
  { iso2: 'CG', name: 'Congo', flag: '🇨🇬' },
  { iso2: 'CD', name: 'DR Congo', flag: '🇨🇩' },
  { iso2: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { iso2: 'HR', name: 'Croatia', flag: '🇭🇷' },
  { iso2: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { iso2: 'CY', name: 'Cyprus', flag: '🇨🇾' },
  { iso2: 'CZ', name: 'Czech Republic', flag: '🇨🇿' },
  { iso2: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { iso2: 'DJ', name: 'Djibouti', flag: '🇩🇯' },
  { iso2: 'DM', name: 'Dominica', flag: '🇩🇲' },
  { iso2: 'DO', name: 'Dominican Republic', flag: '🇩🇴' },
  { iso2: 'EC', name: 'Ecuador', flag: '🇪🇨' },
  { iso2: 'EG', name: 'Egypt', flag: '🇪🇬' },
  { iso2: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { iso2: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶' },
  { iso2: 'ER', name: 'Eritrea', flag: '🇪🇷' },
  { iso2: 'EE', name: 'Estonia', flag: '🇪🇪' },
  { iso2: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { iso2: 'ET', name: 'Ethiopia', flag: '🇪🇹' },
  { iso2: 'FJ', name: 'Fiji', flag: '🇫🇯' },
  { iso2: 'FI', name: 'Finland', flag: '🇫🇮' },
  { iso2: 'FR', name: 'France', flag: '🇫🇷' },
  { iso2: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { iso2: 'GM', name: 'Gambia', flag: '🇬🇲' },
  { iso2: 'GE', name: 'Georgia', flag: '🇬🇪' },
  { iso2: 'DE', name: 'Germany', flag: '🇩🇪' },
  { iso2: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { iso2: 'GR', name: 'Greece', flag: '🇬🇷' },
  { iso2: 'GD', name: 'Grenada', flag: '🇬🇩' },
  { iso2: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { iso2: 'GN', name: 'Guinea', flag: '🇬🇳' },
  { iso2: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼' },
  { iso2: 'GY', name: 'Guyana', flag: '🇬🇾' },
  { iso2: 'HT', name: 'Haiti', flag: '🇭🇹' },
  { iso2: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { iso2: 'HU', name: 'Hungary', flag: '🇭🇺' },
  { iso2: 'IS', name: 'Iceland', flag: '🇮🇸' },
  { iso2: 'IN', name: 'India', flag: '🇮🇳' },
  { iso2: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { iso2: 'IR', name: 'Iran', flag: '🇮🇷' },
  { iso2: 'IQ', name: 'Iraq', flag: '🇮🇶' },
  { iso2: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { iso2: 'IL', name: 'Israel', flag: '🇮🇱' },
  { iso2: 'IT', name: 'Italy', flag: '🇮🇹' },
  { iso2: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮' },
  { iso2: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  { iso2: 'JP', name: 'Japan', flag: '🇯🇵' },
  { iso2: 'JO', name: 'Jordan', flag: '🇯🇴' },
  { iso2: 'KZ', name: 'Kazakhstan', flag: '🇰🇿' },
  { iso2: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { iso2: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { iso2: 'KW', name: 'Kuwait', flag: '🇰🇼' },
  { iso2: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬' },
  { iso2: 'LA', name: 'Laos', flag: '🇱🇦' },
  { iso2: 'LV', name: 'Latvia', flag: '🇱🇻' },
  { iso2: 'LB', name: 'Lebanon', flag: '🇱🇧' },
  { iso2: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { iso2: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { iso2: 'LY', name: 'Libya', flag: '🇱🇾' },
  { iso2: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { iso2: 'LT', name: 'Lithuania', flag: '🇱🇹' },
  { iso2: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  { iso2: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { iso2: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { iso2: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { iso2: 'MV', name: 'Maldives', flag: '🇲🇻' },
  { iso2: 'ML', name: 'Mali', flag: '🇲🇱' },
  { iso2: 'MT', name: 'Malta', flag: '🇲🇹' },
  { iso2: 'MH', name: 'Marshall Islands', flag: '🇲🇭' },
  { iso2: 'MR', name: 'Mauritania', flag: '🇲🇷' },
  { iso2: 'MU', name: 'Mauritius', flag: '🇲🇺' },
  { iso2: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { iso2: 'FM', name: 'Micronesia', flag: '🇫🇲' },
  { iso2: 'MD', name: 'Moldova', flag: '🇲🇩' },
  { iso2: 'MC', name: 'Monaco', flag: '🇲🇨' },
  { iso2: 'MN', name: 'Mongolia', flag: '🇲🇳' },
  { iso2: 'ME', name: 'Montenegro', flag: '🇲🇪' },
  { iso2: 'MA', name: 'Morocco', flag: '🇲🇦' },
  { iso2: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { iso2: 'MM', name: 'Myanmar', flag: '🇲🇲' },
  { iso2: 'NA', name: 'Namibia', flag: '🇳🇦' },
  { iso2: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { iso2: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { iso2: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { iso2: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  { iso2: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
  { iso2: 'NE', name: 'Niger', flag: '🇳🇪' },
  { iso2: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { iso2: 'KP', name: 'North Korea', flag: '🇰🇵' },
  { iso2: 'MK', name: 'North Macedonia', flag: '🇲🇰' },
  { iso2: 'NO', name: 'Norway', flag: '🇳🇴' },
  { iso2: 'OM', name: 'Oman', flag: '🇴🇲' },
  { iso2: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { iso2: 'PW', name: 'Palau', flag: '🇵🇼' },
  { iso2: 'PA', name: 'Panama', flag: '🇵🇦' },
  { iso2: 'PG', name: 'Papua New Guinea', flag: '🇵🇬' },
  { iso2: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { iso2: 'PE', name: 'Peru', flag: '🇵🇪' },
  { iso2: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { iso2: 'PL', name: 'Poland', flag: '🇵🇱' },
  { iso2: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { iso2: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { iso2: 'RO', name: 'Romania', flag: '🇷🇴' },
  { iso2: 'RU', name: 'Russia', flag: '🇷🇺' },
  { iso2: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { iso2: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { iso2: 'LC', name: 'Saint Lucia', flag: '🇱🇨' },
  { iso2: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { iso2: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { iso2: 'SM', name: 'San Marino', flag: '🇸🇲' },
  { iso2: 'ST', name: 'São Tomé and Príncipe', flag: '🇸🇹' },
  { iso2: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { iso2: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { iso2: 'RS', name: 'Serbia', flag: '🇷🇸' },
  { iso2: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { iso2: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { iso2: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { iso2: 'SK', name: 'Slovakia', flag: '🇸🇰' },
  { iso2: 'SI', name: 'Slovenia', flag: '🇸🇮' },
  { iso2: 'SB', name: 'Solomon Islands', flag: '🇸🇧' },
  { iso2: 'SO', name: 'Somalia', flag: '🇸🇴' },
  { iso2: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { iso2: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { iso2: 'SS', name: 'South Sudan', flag: '🇸🇸' },
  { iso2: 'ES', name: 'Spain', flag: '🇪🇸' },
  { iso2: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { iso2: 'SD', name: 'Sudan', flag: '🇸🇩' },
  { iso2: 'SR', name: 'Suriname', flag: '🇸🇷' },
  { iso2: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { iso2: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { iso2: 'SY', name: 'Syria', flag: '🇸🇾' },
  { iso2: 'TW', name: 'Taiwan', flag: '🇹🇼' },
  { iso2: 'TJ', name: 'Tajikistan', flag: '🇹🇯' },
  { iso2: 'TZ', name: 'Tanzania', flag: '🇹🇿' },
  { iso2: 'TH', name: 'Thailand', flag: '🇹🇭' },
  { iso2: 'TL', name: 'Timor-Leste', flag: '🇹🇱' },
  { iso2: 'TG', name: 'Togo', flag: '🇹🇬' },
  { iso2: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { iso2: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹' },
  { iso2: 'TN', name: 'Tunisia', flag: '🇹🇳' },
  { iso2: 'TR', name: 'Turkey', flag: '🇹🇷' },
  { iso2: 'TM', name: 'Turkmenistan', flag: '🇹🇲' },
  { iso2: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { iso2: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { iso2: 'UA', name: 'Ukraine', flag: '🇺🇦' },
  { iso2: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { iso2: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { iso2: 'US', name: 'United States', flag: '🇺🇸' },
  { iso2: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { iso2: 'UZ', name: 'Uzbekistan', flag: '🇺🇿' },
  { iso2: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { iso2: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { iso2: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { iso2: 'YE', name: 'Yemen', flag: '🇾🇪' },
  { iso2: 'ZM', name: 'Zambia', flag: '🇿🇲' },
  { iso2: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' },
  { iso2: 'PS', name: 'Palestine', flag: '🇵🇸' },
  { iso2: 'XK', name: 'Kosovo', flag: '🇽🇰' },
]

const byIso2 = new Map(COUNTRIES.map(c => [c.iso2, c]))

export function getCountry(iso2: string): CountryMeta | undefined {
  return byIso2.get(iso2)
}

export function getCountryName(iso2: string): string {
  return byIso2.get(iso2)?.name ?? iso2
}

export function getFlag(iso2: string): string {
  return byIso2.get(iso2)?.flag ?? '🏳'
}

export function getAllCountries(): CountryMeta[] {
  return COUNTRIES
}

// ISO 3166-1 numeric → ISO-2 (used to decode world-110m.json topojson IDs)
const NUMERIC_TO_ISO2: Record<number, string> = {
  4: 'AF', 8: 'AL', 12: 'DZ', 24: 'AO', 31: 'AZ', 32: 'AR', 36: 'AU',
  40: 'AT', 44: 'BS', 50: 'BD', 51: 'AM', 56: 'BE', 64: 'BT', 68: 'BO',
  70: 'BA', 72: 'BW', 76: 'BR', 84: 'BZ', 90: 'SB', 96: 'BN', 100: 'BG',
  104: 'MM', 108: 'BI', 112: 'BY', 116: 'KH', 120: 'CM', 124: 'CA',
  140: 'CF', 144: 'LK', 148: 'TD', 152: 'CL', 156: 'CN', 158: 'TW',
  170: 'CO', 178: 'CG', 180: 'CD', 188: 'CR', 191: 'HR', 192: 'CU',
  196: 'CY', 203: 'CZ', 204: 'BJ', 208: 'DK', 214: 'DO', 218: 'EC',
  222: 'SV', 226: 'GQ', 231: 'ET', 232: 'ER', 233: 'EE', 242: 'FJ',
  246: 'FI', 250: 'FR', 262: 'DJ', 266: 'GA', 268: 'GE', 270: 'GM',
  275: 'PS', 276: 'DE', 288: 'GH', 300: 'GR', 320: 'GT', 324: 'GN',
  328: 'GY', 332: 'HT', 340: 'HN', 348: 'HU', 352: 'IS', 356: 'IN',
  360: 'ID', 364: 'IR', 368: 'IQ', 372: 'IE', 376: 'IL', 380: 'IT',
  384: 'CI', 388: 'JM', 392: 'JP', 398: 'KZ', 400: 'JO', 404: 'KE',
  408: 'KP', 410: 'KR', 414: 'KW', 417: 'KG', 418: 'LA', 422: 'LB',
  426: 'LS', 428: 'LV', 430: 'LR', 434: 'LY', 440: 'LT', 442: 'LU',
  450: 'MG', 454: 'MW', 458: 'MY', 466: 'ML', 478: 'MR', 484: 'MX',
  496: 'MN', 498: 'MD', 499: 'ME', 504: 'MA', 508: 'MZ', 512: 'OM',
  516: 'NA', 524: 'NP', 528: 'NL', 548: 'VU', 554: 'NZ', 558: 'NI',
  562: 'NE', 566: 'NG', 578: 'NO', 586: 'PK', 591: 'PA', 598: 'PG',
  600: 'PY', 604: 'PE', 608: 'PH', 616: 'PL', 620: 'PT', 624: 'GW',
  626: 'TL', 634: 'QA', 642: 'RO', 643: 'RU', 646: 'RW', 682: 'SA',
  686: 'SN', 688: 'RS', 694: 'SL', 703: 'SK', 704: 'VN', 705: 'SI',
  706: 'SO', 710: 'ZA', 716: 'ZW', 724: 'ES', 728: 'SS', 729: 'SD',
  740: 'SR', 748: 'SZ', 752: 'SE', 756: 'CH', 760: 'SY', 762: 'TJ',
  764: 'TH', 768: 'TG', 780: 'TT', 784: 'AE', 788: 'TN', 792: 'TR',
  795: 'TM', 800: 'UG', 804: 'UA', 807: 'MK', 818: 'EG', 826: 'GB',
  834: 'TZ', 840: 'US', 854: 'BF', 858: 'UY', 860: 'UZ', 862: 'VE',
  887: 'YE', 894: 'ZM',
}

export function numericToIso2(numericId: number | string): string {
  const n = typeof numericId === 'string' ? parseInt(numericId, 10) : numericId
  return NUMERIC_TO_ISO2[n] ?? ''
}
